### ISSUE TITLE
Other TODO items

### ISSUE THREAD

**Issue by matsjoyce** [dwjoyce/pythonbook#10]
- [x] Specify USB location in filesystem.
- [x] Perhaps the previous section on modifying lists should be in the slicing chapter.
- [x] Remove `del`
- [x] Insert a screenshot of the interactive shell on the left and the turtle
  window towards the right (they need not be 50-50). The turtle window should be blank before
  any drawing.
- [x] Provide the location of this guide - is it on the Raspberry Pi desktop for
  them to click on?

**Comment by dwjoyce** [comment]
These issues done - keep this open for further todos or not?
